# Generated by Django 4.1 on 2022-09-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caliber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliber_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_name', models.CharField(max_length=255)),
                ('price_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_ncm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('caliber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricelists.caliber')),
            ],
        ),
    ]
